# Generated by Django 4.2.11 on 2026-02-08 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0004_internaldocument_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('attached_documents', models.FileField(upload_to='agreements/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping_system.importer')),
            ],
        ),
    ]
