# Generated by Django 4.2.11 on 2026-03-08 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping_system', '0005_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_registration', models.CharField(max_length=50)),
                ('manifest_number', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('manifest_file', models.FileField(blank=True, null=True, upload_to='shipments/manifest/')),
                ('waybill_file', models.FileField(blank=True, null=True, upload_to='shipments/waybill/')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='shipments/invoice/')),
                ('comesa_sadc_file', models.FileField(blank=True, null=True, upload_to='shipments/comesa_sadc/')),
                ('cill_number', models.CharField(blank=True, max_length=100)),
                ('bill_of_entry_number', models.CharField(blank=True, max_length=100)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('assessment_number', models.CharField(blank=True, max_length=100)),
                ('date_assessed', models.DateField(blank=True, null=True)),
                ('proof_of_payment_file', models.FileField(blank=True, null=True, upload_to='shipments/proof_of_payment/')),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('date_exited', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_REGISTERED', 'Not Yet Registered – Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment Stage'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], default='NOT_REGISTERED', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('NOT_REGISTERED', 'Not Yet Registered – Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment Stage'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], max_length=20)),
                ('to_status', models.CharField(choices=[('NOT_REGISTERED', 'Not Yet Registered – Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment Stage'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_status_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='shipping_system.truckshipment')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
