# Generated by Django 4.2.11 on 2026-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0006_truckshipment_alter_billofentry_entry_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentry',
            name='entry_number',
            field=models.CharField(error_messages={'unique': 'Entry number already exists. Please enter another entry number.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email already exists. Please enter another email.'}, max_length=254, unique=True),
        ),
    ]
