# Generated by Django 4.2.11 on 2026-03-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0007_alter_billofentry_entry_number_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckshipment',
            name='manifest_file',
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='bill_of_lading_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/bill_of_lading/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='bill_of_lading_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='cbca_coc_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/cbca_coc_certificate/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='container_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='duty_calculation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='ema_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/ema_certificate/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='eta_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='importer_tax_clearance_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/importer_tax_clearance/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/license/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='packing_list_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/packing_list/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='permit_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/permit/'),
        ),
        migrations.AlterField(
            model_name='shipmentstatusevent',
            name='from_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentstatusevent',
            name='to_status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='truckshipment',
            name='status',
            field=models.CharField(choices=[('NOT_REGISTERED', 'Waiting for Documentation'), ('REGISTERED', 'Registered – Waiting Assessment'), ('ASSESSED', 'Assessed – Waiting Payment'), ('PAID', 'Paid – Waiting Proof of Payment'), ('RECEIPTED', 'Receipted – Waiting Cross'), ('RELEASE', 'Release'), ('COMPLETED', 'Completed')], default='NOT_REGISTERED', max_length=20),
        ),
    ]
