# Generated by Django 4.2.11 on 2026-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0008_remove_truckshipment_manifest_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckshipment',
            name='manifest_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/manifest/'),
        ),
        migrations.AddField(
            model_name='truckshipment',
            name='release_order_file',
            field=models.FileField(blank=True, null=True, upload_to='shipments/release_order/'),
        ),
    ]
