# Generated by Django 4.2.11 on 2026-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0009_truckshipment_manifest_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckshipment',
            name='truck_registration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
