# Generated by Django 4.2.11 on 2026-03-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0010_alter_truckshipment_truck_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckshipment',
            name='manifest_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='truckshipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
