# Generated by Django 4.2.11 on 2026-03-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_system', '0011_alter_truckshipment_manifest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckshipment',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_shipments', to='shipping_system.importer'),
        ),
    ]
